### ISSUE TITLE
Error: spawn google chrome ENOENT

### ISSUE THREAD

**Issue by marcusvy** [marcusvy/the-old-man#1]
Erro de execução
```bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn google chrome ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by marcusvy** [comment]
Como o ambiente de produção é o Debian 8 então o navegador Google Chrome não é reconhecido. Basta modificar para um que está instalado (iceweasel, baseado no firefox)
```Javascript
{
  "browserSync": {
    "options": {
      "browser": ["firefox"],
      "open": true
    }
  }
}
```

**Comment by marcusvy** [comment]
On linux the correct use for Google Chrome on BrowserSync configuration is:
```Javascript
{
  "browserSync": {
    "options": {
      "browser": ["google-chrome"],
      "open": true
    }
  }
}
```
